# Generated by Django 3.1.6 on 2021-02-10 01:41

from django.db import migrations, models
import gsheets.mixins
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=127)),
                ('url', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('technology', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
                ('read_more', models.BooleanField(default=False)),
            ],
            bases=(gsheets.mixins.SheetPullableMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=20)),
                ('image', models.FilePathField(path='/img')),
            ],
        ),
    ]
